export const errors = {
  LOGIN_FORM_USERNAME_REQUIRED: "LOGIN_FORM_USERNAME_REQUIRED",
  LOGIN_FORM_PASSWORD_REQUIRED: "LOGIN_FORM_PASSWORD_REQUIRED",
  LOGIN_FORM_USERNAME_EXISTS: "LOGIN_FORM_USERNAME_EXISTS",
  LOGIN_FORM_USERNAME_DOES_NOT_EXIST: "LOGIN_FORM_USERNAME_DOES_NOT_EXIST",
  LOGIN_FORM_INCORRECT_PASSWORD: "LOGIN_FORM_INCORRECT_PASSWORD",
  ERROR_LOGIN_REQUIRED: "ERROR_LOGIN_REQUIRED",
} as const;
export type ErrorEnum = typeof errors[keyof typeof errors];
