export default {
  fragments: [
    {
      begin: "0.000",
      children: [
        {
          begin: "0.000",
          children: [
            {
              begin: "0.000",
              children: [],
              end: "1.930",
              id: "w1",
              language: "isl",
              lines: ["Vinkonur"],
            },
            {
              begin: "1.930",
              children: [],
              end: "2.315",
              id: "w2",
              language: "isl",
              lines: ["vors"],
            },
            {
              begin: "2.315",
              children: [],
              end: "2.365",
              id: "w3",
              language: "isl",
              lines: ["og"],
            },
            {
              begin: "2.365",
              children: [],
              end: "4.400",
              id: "w4",
              language: "isl",
              lines: ["bl\u00f3ma"],
            },
          ],
          end: "4.400",
          id: "s0",
          language: "isl",
          lines: ["Vinkonur vors og bl\u00f3ma"],
        },
        {
          begin: "4.400",
          children: [
            {
              begin: "4.400",
              children: [],
              end: "5.090",
              id: "w6",
              language: "isl",
              lines: ["\u00cdris"],
            },
            {
              begin: "5.090",
              children: [],
              end: "5.590",
              id: "w7",
              language: "isl",
              lines: ["Eva"],
            },
            {
              begin: "5.590",
              children: [],
              end: "5.720",
              id: "w8",
              language: "isl",
              lines: ["og"],
            },
            {
              begin: "5.720",
              children: [],
              end: "6.700",
              id: "w9",
              language: "isl",
              lines: ["Hildur"],
            },
            {
              begin: "6.700",
              children: [],
              end: "6.910",
              id: "w10",
              language: "isl",
              lines: ["r\u00e6\u00f0a"],
            },
            {
              begin: "6.910",
              children: [],
              end: "7.480",
              id: "w11",
              language: "isl",
              lines: ["borgarm\u00e1l"],
            },
          ],
          end: "7.480",
          id: "s5",
          language: "isl",
          lines: ["\u00cdris Eva og Hildur r\u00e6\u00f0a borgarm\u00e1l"],
        },
        {
          begin: "7.480",
          children: [
            {
              begin: "7.480",
              children: [],
              end: "8.330",
              id: "w13",
              language: "isl",
              lines: ["gamla"],
            },
            {
              begin: "8.330",
              children: [],
              end: "8.790",
              id: "w14",
              language: "isl",
              lines: ["f\u00f3lki\u00f0"],
            },
            {
              begin: "8.790",
              children: [],
              end: "8.905",
              id: "w15",
              language: "isl",
              lines: ["\u00e1"],
            },
            {
              begin: "8.905",
              children: [],
              end: "9.825",
              id: "w16",
              language: "isl",
              lines: ["Facebook"],
            },
            {
              begin: "9.825",
              children: [],
              end: "10.035",
              id: "w17",
              language: "isl",
              lines: ["og"],
            },
            {
              begin: "10.035",
              children: [],
              end: "10.365",
              id: "w18",
              language: "isl",
              lines: ["skort"],
            },
            {
              begin: "10.365",
              children: [],
              end: "10.440",
              id: "w19",
              language: "isl",
              lines: ["\u00e1"],
            },
            {
              begin: "10.440",
              children: [],
              end: "11.095",
              id: "w20",
              language: "isl",
              lines: ["sundlaugum"],
            },
            {
              begin: "11.095",
              children: [],
              end: "13.820",
              id: "w21",
              language: "isl",
              lines: ["mi\u00f0sv\u00e6\u00f0is"],
            },
          ],
          end: "13.820",
          id: "s12",
          language: "isl",
          lines: [
            "gamla f\u00f3lki\u00f0 \u00e1 Facebook og skort \u00e1 sundlaugum mi\u00f0sv\u00e6\u00f0is",
          ],
        },
        {
          begin: "13.820",
          children: [
            {
              begin: "13.820",
              children: [],
              end: "13.920",
              id: "w23",
              language: "isl",
              lines: ["\u00c9g"],
            },
            {
              begin: "13.920",
              children: [],
              end: "14.070",
              id: "w24",
              language: "isl",
              lines: ["sat"],
            },
            {
              begin: "14.070",
              children: [],
              end: "14.130",
              id: "w25",
              language: "isl",
              lines: ["\u00e1"],
            },
            {
              begin: "14.130",
              children: [],
              end: "15.115",
              id: "w26",
              language: "isl",
              lines: ["kaffih\u00fasi"],
            },
            {
              begin: "15.115",
              children: [],
              end: "15.265",
              id: "w27",
              language: "isl",
              lines: ["\u00feegar"],
            },
            {
              begin: "15.265",
              children: [],
              end: "15.330",
              id: "w28",
              language: "isl",
              lines: ["\u00e9g"],
            },
            {
              begin: "15.330",
              children: [],
              end: "15.600",
              id: "w29",
              language: "isl",
              lines: ["t\u00f3k"],
            },
            {
              begin: "15.600",
              children: [],
              end: "15.965",
              id: "w30",
              language: "isl",
              lines: ["eftir"],
            },
            {
              begin: "15.965",
              children: [],
              end: "16.115",
              id: "w31",
              language: "isl",
              lines: ["\u00feeim"],
            },
            {
              begin: "16.115",
              children: [],
              end: "16.555",
              id: "w32",
              language: "isl",
              lines: ["\u00cdrisi"],
            },
            {
              begin: "16.555",
              children: [],
              end: "16.930",
              id: "w33",
              language: "isl",
              lines: ["Evu"],
            },
            {
              begin: "16.930",
              children: [],
              end: "17.055",
              id: "w34",
              language: "isl",
              lines: ["og"],
            },
            {
              begin: "17.055",
              children: [],
              end: "17.230",
              id: "w35",
              language: "isl",
              lines: ["Hildi"],
            },
            {
              begin: "17.230",
              children: [],
              end: "18.065",
              id: "w36",
              language: "isl",
              lines: ["t\u00edu"],
            },
            {
              begin: "18.065",
              children: [],
              end: "18.940",
              id: "w37",
              language: "isl",
              lines: ["\u00e1ra"],
            },
            {
              begin: "18.940",
              children: [],
              end: "19.350",
              id: "w38",
              language: "isl",
              lines: ["r\u00falla"],
            },
            {
              begin: "19.350",
              children: [],
              end: "19.635",
              id: "w39",
              language: "isl",
              lines: ["ni\u00f0ur"],
            },
            {
              begin: "19.635",
              children: [],
              end: "20.360",
              id: "w40",
              language: "isl",
              lines: ["Frakkast\u00edginn"],
            },
            {
              begin: "20.360",
              children: [],
              end: "20.440",
              id: "w41",
              language: "isl",
              lines: ["\u00e1"],
            },
            {
              begin: "20.440",
              children: [],
              end: "21.030",
              id: "w42",
              language: "isl",
              lines: ["hj\u00f3labrettunum"],
            },
            {
              begin: "21.030",
              children: [],
              end: "22.580",
              id: "w43",
              language: "isl",
              lines: ["s\u00ednum"],
            },
          ],
          end: "22.580",
          id: "s22",
          language: "isl",
          lines: [
            "\u00c9g sat \u00e1 kaffih\u00fasi \u00feegar \u00e9g t\u00f3k eftir \u00feeim \u00cdrisi Evu og Hildi t\u00edu \u00e1ra r\u00falla ni\u00f0ur Frakkast\u00edginn \u00e1 hj\u00f3labrettunum s\u00ednum",
          ],
        },
        {
          begin: "22.580",
          children: [
            {
              begin: "22.580",
              children: [],
              end: "22.760",
              id: "w45",
              language: "isl",
              lines: ["\u00deegar"],
            },
            {
              begin: "22.760",
              children: [],
              end: "22.895",
              id: "w46",
              language: "isl",
              lines: ["\u00e9g"],
            },
            {
              begin: "22.895",
              children: [],
              end: "23.005",
              id: "w47",
              language: "isl",
              lines: ["var"],
            },
            {
              begin: "23.005",
              children: [],
              end: "23.065",
              id: "w48",
              language: "isl",
              lines: ["\u00e1"],
            },
            {
              begin: "23.065",
              children: [],
              end: "23.555",
              id: "w49",
              language: "isl",
              lines: ["\u00feeirra"],
            },
            {
              begin: "23.555",
              children: [],
              end: "23.670",
              id: "w50",
              language: "isl",
              lines: ["aldri"],
            },
            {
              begin: "23.670",
              children: [],
              end: "23.800",
              id: "w51",
              language: "isl",
              lines: ["voru"],
            },
            {
              begin: "23.800",
              children: [],
              end: "24.355",
              id: "w52",
              language: "isl",
              lines: ["hj\u00f3labretti"],
            },
            {
              begin: "24.355",
              children: [],
              end: "24.480",
              id: "w53",
              language: "isl",
              lines: ["fyrir"],
            },
            {
              begin: "24.480",
              children: [],
              end: "25.800",
              id: "w54",
              language: "isl",
              lines: ["str\u00e1ka"],
            },
            {
              begin: "25.800",
              children: [],
              end: "25.880",
              id: "w55",
              language: "isl",
              lines: ["og"],
            },
            {
              begin: "25.880",
              children: [],
              end: "26.370",
              id: "w56",
              language: "isl",
              lines: ["kannski"],
            },
            {
              begin: "26.370",
              children: [],
              end: "26.680",
              id: "w57",
              language: "isl",
              lines: ["\u00feess"],
            },
            {
              begin: "26.680",
              children: [],
              end: "27.025",
              id: "w58",
              language: "isl",
              lines: ["vegna"],
            },
            {
              begin: "27.025",
              children: [],
              end: "27.215",
              id: "w59",
              language: "isl",
              lines: ["sem"],
            },
            {
              begin: "27.215",
              children: [],
              end: "27.350",
              id: "w60",
              language: "isl",
              lines: ["\u00fe\u00e6r"],
            },
            {
              begin: "27.350",
              children: [],
              end: "27.755",
              id: "w61",
              language: "isl",
              lines: ["v\u00f6ktu"],
            },
            {
              begin: "27.755",
              children: [],
              end: "27.995",
              id: "w62",
              language: "isl",
              lines: ["athygli"],
            },
            {
              begin: "27.995",
              children: [],
              end: "29.840",
              id: "w63",
              language: "isl",
              lines: ["m\u00edna"],
            },
          ],
          end: "29.840",
          id: "s44",
          language: "isl",
          lines: [
            "\u00deegar \u00e9g var \u00e1 \u00feeirra aldri voru hj\u00f3labretti fyrir str\u00e1ka og kannski \u00feess vegna sem \u00fe\u00e6r v\u00f6ktu athygli m\u00edna",
          ],
        },
        {
          begin: "29.840",
          children: [
            {
              begin: "29.840",
              children: [],
              end: "30.310",
              id: "w65",
              language: "isl",
              lines: ["\u00c1kve\u00f0in"],
            },
            {
              begin: "30.310",
              children: [],
              end: "30.400",
              id: "w66",
              language: "isl",
              lines: ["a\u00f0"],
            },
            {
              begin: "30.400",
              children: [],
              end: "30.650",
              id: "w67",
              language: "isl",
              lines: ["hafa"],
            },
            {
              begin: "30.650",
              children: [],
              end: "30.825",
              id: "w68",
              language: "isl",
              lines: ["uppi"],
            },
            {
              begin: "30.825",
              children: [],
              end: "30.910",
              id: "w69",
              language: "isl",
              lines: ["\u00e1"],
            },
            {
              begin: "30.910",
              children: [],
              end: "31.235",
              id: "w70",
              language: "isl",
              lines: ["\u00feeim"],
            },
            {
              begin: "31.235",
              children: [],
              end: "31.360",
              id: "w71",
              language: "isl",
              lines: ["og"],
            },
            {
              begin: "31.360",
              children: [],
              end: "32.030",
              id: "w72",
              language: "isl",
              lines: ["forvitnast"],
            },
            {
              begin: "32.030",
              children: [],
              end: "32.175",
              id: "w73",
              language: "isl",
              lines: ["um"],
            },
            {
              begin: "32.175",
              children: [],
              end: "32.605",
              id: "w74",
              language: "isl",
              lines: ["\u00feetta"],
            },
            {
              begin: "32.605",
              children: [],
              end: "33.480",
              id: "w75",
              language: "isl",
              lines: ["eitursvala"],
            },
            {
              begin: "33.480",
              children: [],
              end: "33.690",
              id: "w76",
              language: "isl",
              lines: ["mi\u00f0b\u00e6jargengi"],
            },
            {
              begin: "33.690",
              children: [],
              end: "33.995",
              id: "w77",
              language: "isl",
              lines: ["fann"],
            },
            {
              begin: "33.995",
              children: [],
              end: "34.230",
              id: "w78",
              language: "isl",
              lines: ["\u00e9g"],
            },
            {
              begin: "34.230",
              children: [],
              end: "35.570",
              id: "w79",
              language: "isl",
              lines: ["\u00fe\u00e6r"],
            },
            {
              begin: "35.570",
              children: [],
              end: "35.650",
              id: "w80",
              language: "isl",
              lines: ["\u00ed"],
            },
            {
              begin: "35.650",
              children: [],
              end: "36.390",
              id: "w81",
              language: "isl",
              lines: ["gegnum"],
            },
            {
              begin: "36.390",
              children: [],
              end: "37.120",
              id: "w82",
              language: "isl",
              lines: ["samstarfskonu"],
            },
            {
              begin: "37.120",
              children: [],
              end: "37.615",
              id: "w83",
              language: "isl",
              lines: ["vinkonu"],
            },
            {
              begin: "37.615",
              children: [],
              end: "39.640",
              id: "w84",
              language: "isl",
              lines: ["minnar"],
            },
          ],
          end: "39.640",
          id: "s64",
          language: "isl",
          lines: [
            "\u00c1kve\u00f0in a\u00f0 hafa uppi \u00e1 \u00feeim og forvitnast um \u00feetta eitursvala mi\u00f0b\u00e6jargengi fann \u00e9g \u00fe\u00e6r \u00ed gegnum samstarfskonu vinkonu minnar",
          ],
        },
        {
          begin: "39.640",
          children: [
            {
              begin: "39.640",
              children: [],
              end: "39.805",
              id: "w86",
              language: "isl",
              lines: ["\u00deegar"],
            },
            {
              begin: "39.805",
              children: [],
              end: "40.125",
              id: "w87",
              language: "isl",
              lines: ["\u00e9g"],
            },
            {
              begin: "40.125",
              children: [],
              end: "40.185",
              id: "w88",
              language: "isl",
              lines: ["hitti"],
            },
            {
              begin: "40.185",
              children: [],
              end: "40.470",
              id: "w89",
              language: "isl",
              lines: ["\u00e1"],
            },
            {
              begin: "40.470",
              children: [],
              end: "40.745",
              id: "w90",
              language: "isl",
              lines: ["\u00fe\u00e6r"],
            },
            {
              begin: "40.745",
              children: [],
              end: "40.970",
              id: "w91",
              language: "isl",
              lines: ["voru"],
            },
            {
              begin: "40.970",
              children: [],
              end: "41.470",
              id: "w92",
              language: "isl",
              lines: ["stelpurnar"],
            },
            {
              begin: "41.470",
              children: [],
              end: "42.115",
              id: "w93",
              language: "isl",
              lines: ["n\u00fdkomnar"],
            },
            {
              begin: "42.115",
              children: [],
              end: "42.175",
              id: "w94",
              language: "isl",
              lines: ["\u00far"],
            },
            {
              begin: "42.175",
              children: [],
              end: "42.660",
              id: "w95",
              language: "isl",
              lines: ["Hlj\u00f3mask\u00e1lagar\u00f0inum"],
            },
            {
              begin: "42.660",
              children: [],
              end: "43.285",
              id: "w96",
              language: "isl",
              lines: ["a\u00f0"],
            },
            {
              begin: "43.285",
              children: [],
              end: "43.570",
              id: "w97",
              language: "isl",
              lines: ["nj\u00f3ta"],
            },
            {
              begin: "43.570",
              children: [],
              end: "43.915",
              id: "w98",
              language: "isl",
              lines: ["s\u00ed\u00f0ustu"],
            },
            {
              begin: "43.915",
              children: [],
              end: "44.205",
              id: "w99",
              language: "isl",
              lines: ["daga"],
            },
            {
              begin: "44.205",
              children: [],
              end: "44.920",
              id: "w100",
              language: "isl",
              lines: ["sumarfr\u00edsins"],
            },
            {
              begin: "44.920",
              children: [],
              end: "45.000",
              id: "w101",
              language: "isl",
              lines: ["\u00e1"],
            },
            {
              begin: "45.000",
              children: [],
              end: "45.430",
              id: "w102",
              language: "isl",
              lines: ["hj\u00f3labrettunum"],
            },
            {
              begin: "45.430",
              children: [],
              end: "45.655",
              id: "w103",
              language: "isl",
              lines: ["sem"],
            },
            {
              begin: "45.655",
              children: [],
              end: "46.455",
              id: "w104",
              language: "isl",
              lines: ["\u00fe\u00e6r"],
            },
            {
              begin: "46.455",
              children: [],
              end: "46.740",
              id: "w105",
              language: "isl",
              lines: ["kalla"],
            },
            {
              begin: "46.740",
              children: [],
              end: "47.195",
              id: "w106",
              language: "isl",
              lines: ["penny"],
            },
            {
              begin: "47.195",
              children: [],
              end: "49.140",
              id: "w107",
              language: "isl",
              lines: ["boards"],
            },
          ],
          end: "49.140",
          id: "s85",
          language: "isl",
          lines: [
            "\u00deegar \u00e9g hitti \u00e1 \u00fe\u00e6r voru stelpurnar n\u00fdkomnar \u00far Hlj\u00f3mask\u00e1lagar\u00f0inum a\u00f0 nj\u00f3ta s\u00ed\u00f0ustu daga sumarfr\u00edsins \u00e1 hj\u00f3labrettunum sem \u00fe\u00e6r kalla penny boards",
          ],
        },
        {
          begin: "49.140",
          children: [
            {
              begin: "49.140",
              children: [],
              end: "50.465",
              id: "w109",
              language: "isl",
              lines: ["Hj\u00f3labretti\u00f0"],
            },
            {
              begin: "50.465",
              children: [],
              end: "50.500",
              id: "w110",
              language: "isl",
              lines: ["er"],
            },
            {
              begin: "50.500",
              children: [],
              end: "50.700",
              id: "w111",
              language: "isl",
              lines: ["\u00feeirra"],
            },
            {
              begin: "50.700",
              children: [],
              end: "51.150",
              id: "w112",
              language: "isl",
              lines: ["helsti"],
            },
            {
              begin: "51.150",
              children: [],
              end: "51.690",
              id: "w113",
              language: "isl",
              lines: ["samg\u00f6ngum\u00e1ti"],
            },
            {
              begin: "51.690",
              children: [],
              end: "52.540",
              id: "w114",
              language: "isl",
              lines: ["og"],
            },
            {
              begin: "52.540",
              children: [],
              end: "53.100",
              id: "w115",
              language: "isl",
              lines: ["\u00feekkja"],
            },
            {
              begin: "53.100",
              children: [],
              end: "53.785",
              id: "w116",
              language: "isl",
              lines: ["\u00fe\u00e6r"],
            },
            {
              begin: "53.785",
              children: [],
              end: "53.945",
              id: "w117",
              language: "isl",
              lines: ["or\u00f0i\u00f0"],
            },
            {
              begin: "53.945",
              children: [],
              end: "54.145",
              id: "w118",
              language: "isl",
              lines: ["g\u00f6tur"],
            },
            {
              begin: "54.145",
              children: [],
              end: "55.035",
              id: "w119",
              language: "isl",
              lines: ["mi\u00f0b\u00e6jarins"],
            },
            {
              begin: "55.035",
              children: [],
              end: "55.315",
              id: "w120",
              language: "isl",
              lines: ["inn"],
            },
            {
              begin: "55.315",
              children: [],
              end: "55.350",
              id: "w121",
              language: "isl",
              lines: ["og"],
            },
            {
              begin: "55.350",
              children: [],
              end: "57.000",
              id: "w122",
              language: "isl",
              lines: ["\u00fat"],
            },
          ],
          end: "57.000",
          id: "s108",
          language: "isl",
          lines: [
            "Hj\u00f3labretti\u00f0 er \u00feeirra helsti samg\u00f6ngum\u00e1ti og \u00feekkja \u00fe\u00e6r or\u00f0i\u00f0 g\u00f6tur mi\u00f0b\u00e6jarins inn og \u00fat",
          ],
        },
        {
          begin: "57.000",
          children: [
            {
              begin: "57.000",
              children: [],
              end: "57.495",
              id: "w124",
              language: "isl",
              lines: ["Saman"],
            },
            {
              begin: "57.495",
              children: [],
              end: "57.550",
              id: "w125",
              language: "isl",
              lines: ["r\u00e6\u00f0a"],
            },
            {
              begin: "57.550",
              children: [],
              end: "58.055",
              id: "w126",
              language: "isl",
              lines: ["\u00fe\u00e6r"],
            },
            {
              begin: "58.055",
              children: [],
              end: "58.195",
              id: "w127",
              language: "isl",
              lines: ["um"],
            },
            {
              begin: "58.195",
              children: [],
              end: "58.775",
              id: "w128",
              language: "isl",
              lines: ["mi\u00f0b\u00e6inn"],
            },
            {
              begin: "58.775",
              children: [],
              end: "58.925",
              id: "w129",
              language: "isl",
              lines: ["og"],
            },
            {
              begin: "58.925",
              children: [],
              end: "59.540",
              id: "w130",
              language: "isl",
              lines: ["samg\u00f6ngur"],
            },
          ],
          end: "59.540",
          id: "s123",
          language: "isl",
          lines: [
            "Saman r\u00e6\u00f0a \u00fe\u00e6r um mi\u00f0b\u00e6inn og samg\u00f6ngur",
          ],
        },
        {
          begin: "59.540",
          children: [
            {
              begin: "59.540",
              children: [],
              end: "60.335",
              id: "w132",
              language: "isl",
              lines: ["gamla"],
            },
            {
              begin: "60.335",
              children: [],
              end: "60.825",
              id: "w133",
              language: "isl",
              lines: ["f\u00f3lki\u00f0"],
            },
            {
              begin: "60.825",
              children: [],
              end: "60.905",
              id: "w134",
              language: "isl",
              lines: ["\u00e1"],
            },
            {
              begin: "60.905",
              children: [],
              end: "62.140",
              id: "w135",
              language: "isl",
              lines: ["Facebook"],
            },
            {
              begin: "62.140",
              children: [],
              end: "62.370",
              id: "w136",
              language: "isl",
              lines: ["og"],
            },
            {
              begin: "62.370",
              children: [],
              end: "62.445",
              id: "w137",
              language: "isl",
              lines: ["skort"],
            },
            {
              begin: "62.445",
              children: [],
              end: "62.495",
              id: "w138",
              language: "isl",
              lines: ["\u00e1"],
            },
            {
              begin: "62.495",
              children: [],
              end: "63.135",
              id: "w139",
              language: "isl",
              lines: ["sundlaugum"],
            },
            {
              begin: "63.135",
              children: [],
              end: "63.225",
              id: "w140",
              language: "isl",
              lines: ["\u00ed"],
            },
            {
              begin: "63.225",
              children: [],
              end: "64.720",
              id: "w141",
              language: "isl",
              lines: ["mi\u00f0borginni"],
            },
          ],
          end: "64.720",
          id: "s131",
          language: "isl",
          lines: [
            "gamla f\u00f3lki\u00f0 \u00e1 Facebook og skort \u00e1 sundlaugum \u00ed mi\u00f0borginni",
          ],
        },
      ],
      end: "64.720",
      id: "root",
      language: "isl",
      lines: [
        "Vinkonur vors og bl\u00f3ma \u00cdris Eva og Hildur r\u00e6\u00f0a borgarm\u00e1l gamla f\u00f3lki\u00f0 \u00e1 Facebook og skort \u00e1 sundlaugum mi\u00f0sv\u00e6\u00f0is \u00c9g sat \u00e1 kaffih\u00fasi \u00feegar \u00e9g t\u00f3k eftir \u00feeim \u00cdrisi Evu og Hildi t\u00edu \u00e1ra r\u00falla ni\u00f0ur Frakkast\u00edginn \u00e1 hj\u00f3labrettunum s\u00ednum \u00deegar \u00e9g var \u00e1 \u00feeirra aldri voru hj\u00f3labretti fyrir str\u00e1ka og kannski \u00feess vegna sem \u00fe\u00e6r v\u00f6ktu athygli m\u00edna \u00c1kve\u00f0in a\u00f0 hafa uppi \u00e1 \u00feeim og forvitnast um \u00feetta eitursvala mi\u00f0b\u00e6jargengi fann \u00e9g \u00fe\u00e6r \u00ed gegnum samstarfskonu vinkonu minnar \u00deegar \u00e9g hitti \u00e1 \u00fe\u00e6r voru stelpurnar n\u00fdkomnar \u00far Hlj\u00f3mask\u00e1lagar\u00f0inum a\u00f0 nj\u00f3ta s\u00ed\u00f0ustu daga sumarfr\u00edsins \u00e1 hj\u00f3labrettunum sem \u00fe\u00e6r kalla penny boards Hj\u00f3labretti\u00f0 er \u00feeirra helsti samg\u00f6ngum\u00e1ti og \u00feekkja \u00fe\u00e6r or\u00f0i\u00f0 g\u00f6tur mi\u00f0b\u00e6jarins inn og \u00fat Saman r\u00e6\u00f0a \u00fe\u00e6r um mi\u00f0b\u00e6inn og samg\u00f6ngur gamla f\u00f3lki\u00f0 \u00e1 Facebook og skort \u00e1 sundlaugum \u00ed mi\u00f0borginni",
      ],
    },
  ],
};
