"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.EASY = exports.GOOD = exports.BAD = exports.C2 = exports.C1 = exports.B2 = exports.B1 = exports.A2 = exports.A1 = exports.VERY_IMPORTANT = exports.IMPORTANT = exports.NORMAL_IMPORTANCE = exports.UNIMPORTANT = exports.VERY_UNIMPORTANT = exports.DIFFICULT_FOR_ADVANCED = exports.DIFFICULT_FOR_INTERMEDIATE = exports.DIFFICULT_FOR_BEGINNERS = exports.NOT_DIFFICULT = exports.USER_LEVEL_ADVANCED = exports.USER_LEVEL_INTERMEDIATE = exports.USER_LEVEL_NOVICE = exports.USER_LEVEL_BEGINNER = void 0;
exports.USER_LEVEL_BEGINNER = 1;
exports.USER_LEVEL_NOVICE = 2;
exports.USER_LEVEL_INTERMEDIATE = 3;
exports.USER_LEVEL_ADVANCED = 4;
exports.NOT_DIFFICULT = 1;
exports.DIFFICULT_FOR_BEGINNERS = 2;
exports.DIFFICULT_FOR_INTERMEDIATE = 3;
exports.DIFFICULT_FOR_ADVANCED = 4;
exports.VERY_UNIMPORTANT = 1;
exports.UNIMPORTANT = 2;
exports.NORMAL_IMPORTANCE = 3;
exports.IMPORTANT = 4;
exports.VERY_IMPORTANT = 5;
exports.A1 = 1;
exports.A2 = 2;
exports.B1 = 3;
exports.B2 = 4;
exports.C1 = 5;
exports.C2 = 6;
exports.BAD = 1;
exports.GOOD = 2;
exports.EASY = 3;
