<?php
# This file was automatically generated by the MediaWiki 1.33.0
# installer. If you make manual changes, please keep track in case you
# need to recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# https://www.mediawiki.org/wiki/Manual:Configuration_settings

# Protect against web entry
if ( !defined( 'MEDIAWIKI' ) ) {
	exit;
}


## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename = "Ylhýra";
$wgMetaNamespace = "Project";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs
## (like /w/index.php/Page_title to /wiki/Page_title) please see:
## https://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath = "";

## The URL path to static resources (images, scripts, etc.)
$wgResourceBasePath = $wgScriptPath;

## The URL path to the logo.  Make sure you change this from the default,
## or else you'll overwrite your logo when you upgrade!
$wgLogo = "$wgResourceBasePath/resources/assets/wiki.png";

## UPO means: this is also a user preference option

$wgEnableEmail = true;
$wgEnableUserEmail = true; # UPO

$wgEnotifUserTalk = false; # UPO
$wgEnotifWatchlist = false; # UPO
$wgEmailAuthentication = true;

# MySQL specific settings
$wgDBprefix = "";

# MySQL table options to use during installation or update
$wgDBTableOptions = "ENGINE=InnoDB, DEFAULT CHARSET=binary";

## Shared memory settings
$wgMainCacheType = CACHE_NONE;
$wgMemCachedServers = [];

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads = false;
#$wgUseImageMagick = true;
#$wgImageMagickConvertCommand = "/usr/bin/convert";

# InstantCommons allows wiki to use images from https://commons.wikimedia.org
$wgUseInstantCommons = false;

# Periodically send a pingback to https://www.mediawiki.org/ with basic data
# about this MediaWiki instance. The Wikimedia Foundation shares this data
# with MediaWiki developers to help guide future development efforts.
$wgPingback = true;

## If you use ImageMagick (or any other shell command) on a
## Linux server, this will need to be set to the name of an
## available UTF-8 locale
$wgShellLocale = "C.UTF-8";

## Set $wgCacheDirectory to a writable directory on the web server
## to make your wiki go slightly faster. The directory should not
## be publicly accessible from the web.
#$wgCacheDirectory = "$IP/cache";

# Site language code, should be one of the list in ./languages/data/Names.php
$wgLanguageCode = "en";

# Changing this will log out all existing sessions.
$wgAuthenticationTokenVersion = "1";

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "";
$wgRightsText = "";
$wgRightsIcon = "";

# Path to the GNU diff3 utility. Used for conflict resolution.
$wgDiff3 = "/usr/bin/diff3";

## Default skin: you can change the default skin. Use the internal symbolic
## names, ie 'vector', 'monobook':
$wgDefaultSkin = "athena";

#wfLoadSkin( 'chameleon' );
#$wgDefaultSkin = "chameleon";
#$egChameleonLayoutFile= __DIR__ . '/skins/chameleon/layouts/clean.xml';

wfLoadSkin( 'Athena' );


# Enabled skins.
# The following skins were automatically enabled:
#wfLoadSkin( 'MonoBook' );
#wfLoadSkin( 'Timeless' );
#wfLoadSkin( 'Vector' );


# End of automatically generated settings.
# Add more configuration options below.


wfLoadExtension( 'StopForumSpam' );
wfLoadExtension( 'ConfirmEdit' );

wfLoadExtension( 'Interwiki' );
// To grant sysops permissions to edit interwiki data
$wgGroupPermissions['sysop']['interwiki'] = true;

# Images from Commons
$wgUseInstantCommons = true;

wfLoadExtension( 'VisualEditor' );
$wgDefaultUserOptions['visualeditor-enable'] = 1;
$wgVirtualRestConfig['modules']['parsoid'] = array(
    // URL to the Parsoid instance
    // Use port 8142 if you use the Debian package
    'url' => 'http://localhost:8142',
    // Parsoid "domain", see below (optional)
    'domain' => 'localhost',
    // Parsoid "prefix", see below (optional)
    'prefix' => 'localhost'
);

wfLoadExtension( 'ParserFunctions' );

$wgGroupPermissions['*']['edit'] = false;
#$wgGroupPermissions['user']['edit'] = false;
#$wgGroupPermissions['sysop']['edit'] = true;

$wgNamespacesWithSubpages[NS_MAIN] = true;

$wgScriptPath	    = "";
$wgArticlePath      = "/$1";
$wgUsePathInfo      = true;
$wgScriptExtension  = ".php";


// Define constants for my additional namespaces.
define("NS_DATA", 3000); // This MUST be even.
define("NS_DATA_TALK", 3001); // This MUST be the following odd integer.
$wgExtraNamespaces[NS_DATA] = "Data";
$wgExtraNamespaces[NS_DATA_TALK] = "Data_talk"; // Note underscores in the namespace name.
define("NS_MANUAL", 3002); // This MUST be even.
define("NS_MANUAL_TALK", 3003); // This MUST be the following odd integer.
$wgExtraNamespaces[NS_MANUAL] = "Manual";
$wgExtraNamespaces[NS_MANUAL_TALK] = "Manual_talk"; // Note underscores in the namespace name.

wfLoadExtension( 'Cite' );


$wgVisualEditorAvailableNamespaces = array(
	NS_MAIN => true, 
	NS_USER => true,
	NS_HELP => true,
	NS_PROJECT => true,
	NS_MANUAL => true,
);

$wgNamespaceContentModels[NS_DATA] = CONTENT_MODEL_JSON;

//wfLoadExtension( 'TemplateStyles' );

$wgDebugLogGroups = array(
	'resourceloader' => '/var/log/mediawiki/resourceloader.log',
	'exception' => '/var/log/mediawiki/exception.log',
	'error' => '/var/log/mediawiki/error.log',
'templatestyles' => '/var/log/mediawiki/somegroup.log',
);

unset ($wgFooterIcons['poweredby']['mediawiki']);

$wgEnableUploads = true; # Enable uploads

require_once "$IP/extensions/HeadScript/HeadScript.php";

$wgHeadScriptCode = <<<'START_END_MARKER'
START_END_MARKER;

$wgFileExtensions = array( 'png', 'gif', 'jpg', 'jpeg', 'doc',
    'xls', 'mpp', 'pdf', 'ppt', 'tiff', 'bmp', 'docx', 'xlsx',
    'pptx', 'ps', 'odt', 'ods', 'odp', 'odg', 'svg'
);


$wgRestrictDisplayTitle = false;
$wgDefaultRobotPolicy = 'noindex,nofollow';

$wgRawHtml = true;
