<?php
//  Derived from the Athena skin.
//  https://www.mediawiki.org/wiki/Skin:Athena
//  License: GPL-3.0+
?>
<?php $this->html( 'headelement' ); ?>

<header>
	<div>
		<a href="/" id="logo"></a>
		<ul>
			<li><a href="/Ylhýra">Texts</a></li>
			<li><a href="/Course">Course</a></li>
			<li><a href="/Project:About">About</a></li>
			<li class="user-show"><a href="/Project:Ylhýra">Project</a></li>
		</ul>
	</div>
	<div class="hidden">
	<h1>The page appears not to be working, please <a href="mailto:egillsigurdur@gmail.com">email me</a></h1><br/><br/><br/><br/>
	</div>
</header>


<div id="mw-js-message"></div>
<?php if ( $this->data['newtalk'] ): ?><div class="usermessage"><?php $this->html( 'newtalk' ); ?></div><?php endif; ?>
<?php if ( $this->data['sitenotice'] ): ?><div id="siteNotice"><?php $this->html( 'sitenotice' ) ?></div><?php endif; ?>

<div id="container">
<div id="content">
	<h1 id="title">
		<span class="namespace"><?=$this->getSkin()->getTitle()->getNsText();?></span>
		<?=$this->data[ 'titletext' ];?>
	</h1>

	<?php if ( $this->data['subtitle'] ): ?>
	<div id="subtitle"><?php $this->html( 'subtitle' ) ?></div>
	<?php endif; ?>

	<?php if ( $this->data['undelete'] ): ?>
	<div id="undelete"><?php $this->html( 'undelete' ) ?></div>
	<?php endif; ?>

	<?php if ( $this->data['newtalk'] ): ?>
	<div class="newtalk"><?php $this->html( 'newtalk' )  ?></div>
	<?php endif; ?>

	<?php $this->html( 'bodytext' ) ?>

	<?php $this->html( 'catlinks' ); ?>

	<?php $this->html( 'dataAfterContent' ); ?>

	<div class="printfooter"><?php $this->html( 'printfooter' ); ?></div>

	<?php /*echo $this->getFooter();*/ ?>

	<ul id="actions" class="user-show">
		<?php
		foreach ( $this->data['content_navigation']['namespaces'] as $key => $item ) {
			echo $this->makeListItem( $key, $item, [
				'vector-wrap' => true,
			] );
		}
		?>
		<?php foreach ( $this->getActions() as $key => $value ) echo $this->makeListItem( $key, $value ); ?>
	</ul>

	<?php $this->html( 'debughtml' ); ?>

</div>

<div id="sidebar">
	<div>
		<div>
			<form id="search-form" action="<?php $this->text( 'wgScript' ); ?>">
				<?php echo $this->makeSearchInput( array( 'type' => 'text', 'id' => 'search-field', 'placeholder' => wfMessage( 'athena-search' ), 'autofocus' => false ) ); ?><button><img src="<?php global $wgStylePath; echo $wgStylePath; ?>/Athena/images/lens.png"></button>
				<input type="hidden" name="title" value="<?php $this->text( 'searchtitle' ) ?>" />
			</form>

			<div class="anonymous-show">
				<ul class="anonymous-show portal">
					<li><a href="/Project:Contact">Contact</a>
					<li><a href="/Project:Become_a_collaborator" title="Project:Become a collaborator">Become a collaborator</a></li>
					<?php foreach ( $this->getPersonalTools() as $key => $value ) echo $this->makeListItem( $key, $value ); ?>
				</ul>
			</div>

			<ul class="portal user-show">
			<?php foreach ( $this->data['sidebar']['navigation'] as $key => $value ) echo $this->makeListItem( $key, $value ); ?>
			</ul>
		</div>
		<div class="user-show">
			<h5><?php echo wfMessage( 'athena-personal' ); ?></h5>
			<ul class="portal">
			<?php foreach ( $this->getPersonalTools() as $key => $value ) echo $this->makeListItem( $key, $value ); ?>
			</ul>
		</div>
		<div class="user-show">
			<h5><?php echo wfMessage( 'athena-tools' ); ?></h5>
			<ul class="portal user-show">
			<?php foreach ( $this->getToolbox() as $key => $value ) echo $this->makeListItem( $key, $value ); ?>
			</ul>
		</div>
	</div>
	<div id="free">
		<div>
			Text may be freely copied under the <a href="/Project:License">CC-BY-SA-4.0</a> license unless otherwise specified.
		</div>
	</div>
</div>
</div>

<?php $this->printTrail(); ?>

</body>
</html>
