<?php
//  Derived from the Athena skin.
//  https://www.mediawiki.org/wiki/Skin:Athena
//  License: GPL-3.0+
?>
<?php $this->html( 'headelement' ); ?>

<header>
	<div>
		<a href="/" id="logo"></a>
		<ul>
			<li><a href="/Ylhýra">Texts</a></li>
			<li><a href="/Course">Course</a></li>
			<li><a href="/Project:About">About</a></li>
			<li class="user-show"><a href="/Project:Ylhýra">Project</a></li>
		</ul>
	</div>
</header>


<div id="mw-js-message"></div>
<?php if ( $this->data['newtalk'] ): ?><div class="usermessage"><?php $this->html( 'newtalk' ); ?></div><?php endif; ?>
<?php if ( $this->data['sitenotice'] ): ?><div id="siteNotice"><?php $this->html( 'sitenotice' ) ?></div><?php endif; ?>

<div id="container">
<div id="content">
	<h1 id="title">
ha?
<? print("lol");?>
		<?php
print json_encode($this->data)
			print preg_replace('/(roj)/','HAHA', $this->data[ 'title' ]);
		?>
	</h1>

	<?php if ( $this->data['subtitle'] ): ?>
	<div id="subtitle"><?php $this->html( 'subtitle' ) ?></div>
	<?php endif; ?>

	<?php if ( $this->data['undelete'] ): ?>
	<div id="undelete"><?php $this->html( 'undelete' ) ?></div>
	<?php endif; ?>

	<?php if ( $this->data['newtalk'] ): ?>
	<div class="newtalk"><?php $this->html( 'newtalk' )  ?></div>
	<?php endif; ?>

	<?php $this->html( 'bodytext' ) ?>

	<?php $this->html( 'catlinks' ); ?>

	<?php $this->html( 'dataAfterContent' ); ?>

	<div class="printfooter"><?php $this->html( 'printfooter' ); ?></div>

	<?php /*echo $this->getFooter();*/ ?>

	<ul id="actions">
		<?php
		foreach ( $this->data['content_navigation']['namespaces'] as $key => $item ) {
			echo $this->makeListItem( $key, $item, [
				'vector-wrap' => true,
			] );
		}
		?>
		<?php foreach ( $this->getActions() as $key => $value ) echo $this->makeListItem( $key, $value ); ?>
	</ul>

	<?php $this->html( 'debughtml' ); ?>

</div>

<div id="sidebar">
	<div>
		<div>
			<form id="search-form" action="<?php $this->text( 'wgScript' ); ?>">
				<?php echo $this->makeSearchInput( array( 'type' => 'text', 'id' => 'search-field', 'placeholder' => wfMessage( 'athena-search' ), 'autofocus' => false ) ); ?><button><img src="<?php global $wgStylePath; echo $wgStylePath; ?>/Athena/images/lens.png"></button>
				<input type="hidden" name="title" value="<?php $this->text( 'searchtitle' ) ?>" />
			</form>

			<ul class="portal">
			<?php foreach ( $this->data['sidebar']['navigation'] as $key => $value ) echo $this->makeListItem( $key, $value ); ?>
			</ul>
		</div>
		<div>
			<h5><?php echo wfMessage( 'athena-personal' ); ?></h5>
			<ul class="portal">
			<?php foreach ( $this->getPersonalTools() as $key => $value ) echo $this->makeListItem( $key, $value ); ?>
			</ul>
		</div>
		<div>
			<h5><?php echo wfMessage( 'athena-tools' ); ?></h5>
			<ul class="portal">
			<?php foreach ( $this->getToolbox() as $key => $value ) echo $this->makeListItem( $key, $value ); ?>
			</ul>
		</div>
	</div>
</div>
</div>

<?php $this->printTrail(); ?>

</body>
</html>
